name: stagexl_gaf
version: 0.1.3
author: Bernhard Pichler <support@stagexl.org>
description: The GAF runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_GAF

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  browser: any
  archive: any
  stagexl: '^1.0.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true
