name: stagexl_gaf
version: 0.2.0-dev
author: Bernhard Pichler <support@stagexl.org>
description: The GAF runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_GAF

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  archive: '>=2.0.0 <3.0.0'
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_test: ^0.10.3+1
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.2+1
