name: stagexl_gaf
version: 0.2.0-dev
author: Bernhard Pichler <support@stagexl.org>
description: The GAF runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_GAF

environment:
  sdk: '>=2.0.0-dev.36 <2.0.0'

dependencies:
  archive: any
  stagexl:
      version: '>=1.3.2-dev <2.0.0'
      git: https://github.com/bp74/StageXL

dev_dependencies:
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0+3